TOPOLOGY_LIBRARY = {
    "composite_pipeline": {
        "name": "Composite Multi-Stage Pipeline",
        "category": "composite",
        "constraint_template": "composite_pipeline",
        "complexity": "high",
        "simulation_plan": {
            "analyses": ["op", "ac", "tran"],
            "intent": "Validate end-to-end behavior for cascaded stages selected by topology planning.",
            "primary_metrics": ["gain_db", "bandwidth_hz", "power_mw"],
            "required_constraint_targets": ["supply_v"],
        },
    },
    "rc_lowpass": {
        "name": "Single-Stage RC Low-Pass Filter",
        "category": "filter",
        "constraint_template": "filter_rc",
        "complexity": "low",
        "simulation_plan": {
            "analyses": ["ac", "tran"],
            "intent": "Verify cutoff frequency in AC and confirm step-settling behavior in transient.",
            "primary_metrics": ["fc_hz"],
            "required_constraint_targets": ["target_fc_hz"],
        },
    },
    "rlc_lowpass_2nd_order": {
        "name": "Second-Order RLC Low-Pass Filter",
        "category": "filter",
        "constraint_template": "filter_rlc_lowpass",
        "complexity": "medium",
        "simulation_plan": {
            "analyses": ["ac", "tran"],
            "intent": "Validate second-order low-pass behavior, cutoff, damping, and step response for a targeted response family.",
            "primary_metrics": ["fc_hz", "q_factor", "damping_ratio", "rolloff_db_per_dec"],
            "required_constraint_targets": ["target_fc_hz"],
        },
    },
    "rlc_highpass_2nd_order": {
        "name": "Second-Order RLC High-Pass Filter",
        "category": "filter",
        "constraint_template": "filter_rlc_highpass",
        "complexity": "medium",
        "simulation_plan": {
            "analyses": ["ac", "tran"],
            "intent": "Validate second-order high-pass behavior, cutoff, damping, and high-frequency passband behavior.",
            "primary_metrics": ["fc_hz", "q_factor", "damping_ratio", "rolloff_db_per_dec"],
            "required_constraint_targets": ["target_fc_hz"],
        },
    },
    "rlc_bandpass_2nd_order": {
        "name": "Second-Order RLC Band-Pass Filter",
        "category": "filter",
        "constraint_template": "filter_rlc_bandpass",
        "complexity": "medium",
        "simulation_plan": {
            "analyses": ["ac", "tran"],
            "intent": "Validate center frequency, bandwidth, and selectivity for a second-order RLC band-pass section.",
            "primary_metrics": ["center_hz", "bandwidth_hz", "q_factor"],
            "required_constraint_targets": ["target_center_hz", "target_bw_hz"],
        },
    },
    "current_mirror": {
        "name": "MOS Current Mirror",
        "category": "bias",
        "constraint_template": "bias_current_mirror",
        "complexity": "low",
        "simulation_plan": {
            "analyses": ["op", "dc"],
            "intent": "Check bias current at the operating point and output-current compliance across a DC sweep.",
            "primary_metrics": ["iout_a"],
            "required_constraint_targets": ["target_iout_a", "compliance_v"],
        },
    },
    "wilson_current_mirror": {
        "name": "Wilson Current Mirror",
        "category": "bias",
        "constraint_template": "bias_current_mirror_precision",
        "complexity": "medium",
        "simulation_plan": {
            "analyses": ["op", "dc"],
            "intent": "Validate mirrored current accuracy and output compliance across a DC sweep.",
            "primary_metrics": ["iout_a"],
            "required_constraint_targets": ["target_iout_a"],
        },
    },
    "cascode_current_mirror": {
        "name": "Cascode Current Mirror",
        "category": "bias",
        "constraint_template": "bias_current_mirror_high_output_resistance",
        "complexity": "medium",
        "simulation_plan": {
            "analyses": ["op", "dc"],
            "intent": "Validate mirrored current and confirm high output resistance over a DC compliance sweep.",
            "primary_metrics": ["iout_a"],
            "required_constraint_targets": ["target_iout_a"],
        },
    },
    "wide_swing_current_mirror": {
        "name": "Wide-Swing Cascode Current Mirror",
        "category": "bias",
        "constraint_template": "bias_current_mirror_high_output_resistance",
        "complexity": "medium",
        "simulation_plan": {
            "analyses": ["op", "dc"],
            "intent": "Validate mirrored current and low-headroom compliance for wide-swing operation.",
            "primary_metrics": ["iout_a"],
            "required_constraint_targets": ["target_iout_a", "compliance_v"],
        },
    },
    "widlar_current_mirror": {
        "name": "Widlar Current Mirror",
        "category": "bias",
        "constraint_template": "bias_current_mirror_precision",
        "complexity": "medium",
        "simulation_plan": {
            "analyses": ["op", "dc"],
            "intent": "Validate low-current bias generation and output-current compliance across a DC sweep.",
            "primary_metrics": ["iout_a"],
            "required_constraint_targets": ["target_iout_a", "compliance_v"],
        },
    },
    "common_source_res_load": {
        "name": "Common-Source Amplifier with Resistive Load",
        "category": "amplifier",
        "constraint_template": "amplifier_single_stage",
        "complexity": "medium",
        "simulation_plan": {
            "analyses": ["op", "ac", "tran"],
            "intent": "Check bias point first, then verify small-signal gain, bandwidth, and large-signal transient response.",
            "primary_metrics": ["gain_db", "bandwidth_hz", "power_mw"],
            "required_constraint_targets": ["target_gain_db", "target_bw_hz", "power_limit_mw"],
        },
    },
    "diff_pair": {
        "name": "MOS Differential Pair",
        "category": "amplifier",
        "constraint_template": "amplifier_differential",
        "complexity": "medium",
        "simulation_plan": {
            "analyses": ["op", "ac", "tran"],
            "intent": "Check differential pair biasing, verify differential gain, and inspect transient differential output behavior.",
            "primary_metrics": ["gain_db", "bandwidth_hz", "power_mw"],
            "required_constraint_targets": ["power_limit_mw"],
        },
    },
    "diff_pair_resistor_load": {
        "name": "Differential Pair with Resistive Loads",
        "category": "amplifier",
        "constraint_template": "amplifier_differential",
        "complexity": "medium",
        "simulation_plan": {
            "analyses": ["op", "ac", "tran"],
            "intent": "Evaluate differential gain, bandwidth, and power with explicit resistor loads.",
            "primary_metrics": ["gain_db", "bandwidth_hz", "power_mw"],
            "required_constraint_targets": ["power_limit_mw"],
        },
    },
    "diff_pair_current_mirror_load": {
        "name": "Differential Pair with Current-Mirror Loads",
        "category": "amplifier",
        "constraint_template": "amplifier_differential",
        "complexity": "high",
        "simulation_plan": {
            "analyses": ["op", "ac", "tran"],
            "intent": "Validate gain and output swing from active mirror loads in a differential front-end.",
            "primary_metrics": ["gain_db", "bandwidth_hz", "power_mw"],
            "required_constraint_targets": ["power_limit_mw", "target_gain_db"],
        },
    },
    "diff_pair_active_load": {
        "name": "Differential Pair with PMOS Active Loads",
        "category": "amplifier",
        "constraint_template": "amplifier_differential",
        "complexity": "high",
        "simulation_plan": {
            "analyses": ["op", "ac", "tran"],
            "intent": "Validate active-load differential front-end gain, bandwidth, and power behavior.",
            "primary_metrics": ["gain_db", "bandwidth_hz", "power_mw"],
            "required_constraint_targets": ["power_limit_mw", "target_gain_db"],
        },
    },
    "bjt_diff_pair": {
        "name": "BJT Differential Pair",
        "category": "amplifier",
        "constraint_template": "amplifier_differential_bjt",
        "complexity": "medium",
        "simulation_plan": {
            "analyses": ["op", "ac"],
            "intent": "Check BJT biasing and confirm differential small-signal behavior.",
            "primary_metrics": ["gain_db", "bandwidth_hz"],
            "required_constraint_targets": ["tail_current_a", "collector_res_ohm"],
        },
    },
    "gm_stage": {
        "name": "Transconductance Stage",
        "category": "analog_block",
        "constraint_template": "transconductor",
        "complexity": "medium",
        "simulation_plan": {
            "analyses": ["op", "ac", "tran"],
            "intent": "Validate target transconductance and inspect both frequency response and step behavior.",
            "primary_metrics": ["gain_db", "bandwidth_hz"],
            "required_constraint_targets": ["target_gm_s"],
        },
    },
    "common_drain": {
        "name": "Common-Drain Source Follower",
        "category": "amplifier",
        "constraint_template": "source_follower",
        "complexity": "medium",
        "simulation_plan": {
            "analyses": ["op", "ac", "tran"],
            "intent": "Check source-follower biasing, bandwidth, and large-signal following behavior.",
            "primary_metrics": ["gain_db", "bandwidth_hz", "power_mw"],
            "required_constraint_targets": ["supply_v", "target_gm_s"],
        },
    },
    "adc_input_buffer": {
        "name": "ADC Input Buffer",
        "category": "adc_support",
        "constraint_template": "source_follower",
        "complexity": "medium",
        "simulation_plan": {
            "analyses": ["op", "ac", "tran"],
            "intent": "Validate source-follower style ADC input buffering for bandwidth and drive margin.",
            "primary_metrics": ["gain_db", "bandwidth_hz", "power_mw"],
            "required_constraint_targets": ["supply_v", "target_gm_s"],
        },
    },
    "adc_reference_buffer": {
        "name": "ADC Reference Buffer",
        "category": "adc_support",
        "constraint_template": "source_follower",
        "complexity": "medium",
        "simulation_plan": {
            "analyses": ["op", "ac", "tran"],
            "intent": "Validate buffered reference drive path with stable transient settling behavior.",
            "primary_metrics": ["gain_db", "bandwidth_hz", "power_mw"],
            "required_constraint_targets": ["supply_v", "target_gm_s"],
        },
    },
    "dac_output_buffer": {
        "name": "DAC Output Buffer",
        "category": "dac_support",
        "constraint_template": "source_follower",
        "complexity": "medium",
        "simulation_plan": {
            "analyses": ["op", "ac", "tran"],
            "intent": "Validate DAC output-buffer drive capability, bandwidth, and quiescent power.",
            "primary_metrics": ["gain_db", "bandwidth_hz", "power_mw"],
            "required_constraint_targets": ["supply_v", "target_gm_s"],
        },
    },
    "common_gate": {
        "name": "Common-Gate Amplifier",
        "category": "amplifier",
        "constraint_template": "common_gate_amp",
        "complexity": "medium",
        "simulation_plan": {
            "analyses": ["op", "ac", "tran"],
            "intent": "Check bias headroom, then verify AC response and transient signal handling.",
            "primary_metrics": ["gain_db", "bandwidth_hz", "power_mw"],
            "required_constraint_targets": ["supply_v", "target_gm_s"],
        },
    },
    "source_degenerated_cs": {
        "name": "Source-Degenerated Common-Source Amplifier",
        "category": "amplifier",
        "constraint_template": "amplifier_source_degenerated",
        "complexity": "medium",
        "simulation_plan": {
            "analyses": ["op", "ac", "tran"],
            "intent": "Check linearized biasing, verify moderate gain with bandwidth control, and confirm transient step response.",
            "primary_metrics": ["gain_db", "bandwidth_hz", "power_mw"],
            "required_constraint_targets": ["target_gain_db", "target_bw_hz", "power_limit_mw"],
        },
    },
    "transimpedance_frontend": {
        "name": "Transimpedance Sensor Front-End",
        "category": "sensor_frontend",
        "constraint_template": "amplifier_single_stage",
        "complexity": "high",
        "simulation_plan": {
            "analyses": ["op", "ac", "tran", "noise"],
            "intent": "Validate transimpedance gain, bandwidth, and first-pass transient response for sensor current inputs.",
            "primary_metrics": ["gain_db", "bandwidth_hz", "power_mw"],
            "required_constraint_targets": ["target_gain_db", "target_bw_hz", "power_limit_mw"],
        },
    },
    "common_source_active_load": {
        "name": "Common-Source Amplifier with Active Load",
        "category": "amplifier",
        "constraint_template": "amplifier_active_load",
        "complexity": "medium",
        "simulation_plan": {
            "analyses": ["op", "ac", "tran"],
            "intent": "Check active-load biasing, confirm achievable small-signal gain and bandwidth, and inspect transient swing.",
            "primary_metrics": ["gain_db", "bandwidth_hz", "power_mw"],
            "required_constraint_targets": ["target_gain_db", "power_limit_mw"],
        },
    },
    "diode_connected_stage": {
        "name": "Diode-Connected MOS Amplifier",
        "category": "amplifier",
        "constraint_template": "amplifier_active_load",
        "complexity": "medium",
        "simulation_plan": {
            "analyses": ["op", "ac", "tran"],
            "intent": "Check diode-connected load biasing, confirm first-pass gain behavior, and inspect transient output response.",
            "primary_metrics": ["gain_db", "bandwidth_hz", "power_mw"],
            "required_constraint_targets": ["target_gain_db", "power_limit_mw"],
        },
    },
    "cascode_amplifier": {
        "name": "NMOS Cascode Amplifier",
        "category": "amplifier",
        "constraint_template": "amplifier_cascode",
        "complexity": "high",
        "simulation_plan": {
            "analyses": ["op", "ac", "tran"],
            "intent": "Check cascode headroom, confirm gain improvement with AC response, and inspect transient swing limits.",
            "primary_metrics": ["gain_db", "bandwidth_hz", "power_mw"],
            "required_constraint_targets": ["target_gain_db", "power_limit_mw"],
        },
    },
    "nand2_cmos": {
        "name": "CMOS 2-Input NAND Gate",
        "category": "digital",
        "constraint_template": "digital_cmos_gate",
        "complexity": "medium",
        "simulation_plan": {
            "analyses": ["tran"],
            "intent": "Verify logic behavior and timing transitions for representative input toggles.",
            "primary_metrics": [],
            "required_constraint_targets": ["supply_v"],
        },
    },
    "sram6t_cell": {
        "name": "6T SRAM Cell",
        "category": "memory",
        "constraint_template": "memory_sram_cell",
        "complexity": "high",
        "simulation_plan": {
            "analyses": ["tran"],
            "intent": "Verify write/read state behavior through transient storage-node trajectories.",
            "primary_metrics": ["q_final_v", "qb_final_v", "write_ok"],
            "required_constraint_targets": ["supply_v"],
        },
    },
    "lc_oscillator_cross_coupled": {
        "name": "Cross-Coupled LC Oscillator",
        "category": "oscillator",
        "constraint_template": "oscillator_lc",
        "complexity": "high",
        "simulation_plan": {
            "analyses": ["tran"],
            "intent": "Confirm startup and estimate oscillation frequency from transient tank behavior.",
            "primary_metrics": ["oscillation_hz"],
            "required_constraint_targets": ["target_osc_hz", "supply_v"],
        },
    },
    "bandgap_reference_core": {
        "name": "Bandgap Reference Core",
        "category": "reference",
        "constraint_template": "reference_bandgap",
        "complexity": "high",
        "simulation_plan": {
            "analyses": ["op", "dc", "tran"],
            "intent": "Check operating-point reference voltage, line regulation in DC, and settling in transient.",
            "primary_metrics": ["vref_v"],
            "required_constraint_targets": ["target_vref_v", "supply_v"],
        },
    },
    "dac_reference_conditioning": {
        "name": "DAC Reference Conditioning RC",
        "category": "dac_support",
        "constraint_template": "filter_rc",
        "complexity": "low",
        "simulation_plan": {
            "analyses": ["ac", "tran"],
            "intent": "Condition and deglitch the DAC reference using a first-order RC network.",
            "primary_metrics": ["fc_hz"],
            "required_constraint_targets": ["target_fc_hz"],
        },
    },
    "adc_anti_alias_rc": {
        "name": "ADC Anti-Alias RC Filter",
        "category": "adc_support",
        "constraint_template": "filter_rc",
        "complexity": "low",
        "simulation_plan": {
            "analyses": ["ac", "tran"],
            "intent": "Validate anti-alias filtering cutoff and transient behavior at the ADC input.",
            "primary_metrics": ["fc_hz"],
            "required_constraint_targets": ["target_fc_hz"],
        },
    },
    "compensation_network_helper": {
        "name": "Compensation Network Helper",
        "category": "power_support",
        "constraint_template": "filter_rc",
        "complexity": "low",
        "simulation_plan": {
            "analyses": ["ac", "tran"],
            "intent": "Evaluate compensation pole/zero helper network for control-loop shaping studies.",
            "primary_metrics": ["fc_hz"],
            "required_constraint_targets": ["target_fc_hz"],
        },
    },
    "two_stage_miller": {
        "name": "Two-Stage Op-Amp with Miller Compensation",
        "category": "opamp",
        "constraint_template": "opamp_two_stage",
        "complexity": "high",
        "simulation_plan": {
            "analyses": ["op", "ac", "tran"],
            "intent": "Check bias point, open-loop gain and bandwidth, then verify large-signal settling and slew behavior.",
            "primary_metrics": ["gain_db", "bandwidth_hz"],
            "required_constraint_targets": ["target_gain_db", "target_ugbw_hz", "phase_margin_deg", "power_limit_mw"],
        },
    },
    "telescopic_cascode_opamp_core": {
        "name": "Telescopic Cascode Op-Amp Core",
        "category": "opamp",
        "constraint_template": "opamp_two_stage",
        "complexity": "high",
        "simulation_plan": {
            "analyses": ["op", "ac", "tran"],
            "intent": "Validate telescopic-cascode OTA core gain, UGBW, and transient settling behavior.",
            "primary_metrics": ["gain_db", "ugbw_hz", "power_mw"],
            "required_constraint_targets": ["target_gain_db", "target_ugbw_hz", "power_limit_mw"],
        },
    },
    "folded_cascode_opamp": {
        "name": "Folded Cascode Op-Amp",
        "category": "opamp",
        "constraint_template": "opamp_folded_cascode",
        "complexity": "high",
        "simulation_plan": {
            "analyses": ["op", "ac", "tran"],
            "intent": "Check folded-cascode biasing and confirm gain, unity-gain bandwidth, and transient settling behavior.",
            "primary_metrics": ["gain_db", "ugbw_hz", "power_mw"],
            "required_constraint_targets": ["target_gain_db", "target_ugbw_hz", "power_limit_mw"],
        },
    },
    "folded_cascode_opamp_core": {
        "name": "Folded Cascode Op-Amp Core",
        "category": "opamp",
        "constraint_template": "opamp_folded_cascode",
        "complexity": "high",
        "simulation_plan": {
            "analyses": ["op", "ac", "tran"],
            "intent": "Validate folded-cascode OTA core for gain, unity-gain bandwidth, and power.",
            "primary_metrics": ["gain_db", "ugbw_hz", "power_mw"],
            "required_constraint_targets": ["target_gain_db", "target_ugbw_hz", "power_limit_mw"],
        },
    },
    "ldo_error_amp_core": {
        "name": "LDO Error Amplifier Core",
        "category": "power_support",
        "constraint_template": "opamp_two_stage",
        "complexity": "high",
        "simulation_plan": {
            "analyses": ["op", "ac", "tran"],
            "intent": "Evaluate LDO error-amplifier building block gain/UGBW/power before full regulator integration.",
            "primary_metrics": ["gain_db", "ugbw_hz", "power_mw"],
            "required_constraint_targets": ["target_gain_db", "target_ugbw_hz", "power_limit_mw"],
        },
    },
    "current_sense_amp_helper": {
        "name": "Current Sense Amplifier Helper",
        "category": "power_support",
        "constraint_template": "amplifier_differential",
        "complexity": "medium",
        "simulation_plan": {
            "analyses": ["op", "ac", "tran"],
            "intent": "Validate differential current-sense helper gain and bandwidth under finite power budget.",
            "primary_metrics": ["gain_db", "bandwidth_hz", "power_mw"],
            "required_constraint_targets": ["power_limit_mw", "target_gain_db"],
        },
    },
    "active_filter_stage": {
        "name": "Active Filter Stage (2nd Order)",
        "category": "filter",
        "constraint_template": "filter_rlc_lowpass",
        "complexity": "medium",
        "simulation_plan": {
            "analyses": ["ac", "tran"],
            "intent": "Validate active-filter-stage cutoff and transient shape for signal-chain composition.",
            "primary_metrics": ["fc_hz", "q_factor", "damping_ratio"],
            "required_constraint_targets": ["target_fc_hz"],
        },
    },
    "comparator": {
        "name": "Differential Comparator",
        "category": "mixed_signal",
        "constraint_template": "comparator",
        "complexity": "medium",
        "simulation_plan": {
            "analyses": ["tran"],
            "intent": "Verify regenerative decision behavior, output polarity, and delay in transient.",
            "primary_metrics": ["decision_delay_s", "decision_correct"],
            "required_constraint_targets": ["supply_v", "input_overdrive_v"],
        },
    },
    "static_comparator": {
        "name": "Static Comparator",
        "category": "mixed_signal",
        "constraint_template": "comparator",
        "complexity": "medium",
        "simulation_plan": {
            "analyses": ["op", "tran"],
            "intent": "Validate static comparator decision polarity and delay for small input overdrive.",
            "primary_metrics": ["decision_delay_s", "decision_correct"],
            "required_constraint_targets": ["supply_v", "input_overdrive_v"],
        },
    },
    "latched_comparator": {
        "name": "Latched Comparator",
        "category": "mixed_signal",
        "constraint_template": "comparator",
        "complexity": "medium",
        "simulation_plan": {
            "analyses": ["tran"],
            "intent": "Validate regenerative latched comparator decision speed and output correctness.",
            "primary_metrics": ["decision_delay_s", "decision_correct"],
            "required_constraint_targets": ["supply_v", "input_overdrive_v"],
        },
    },
}
